spring:
  application:
    name: Hospital API
  datasource:
    url: jdbc:h2:mem:paciente
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enable: true
      path: /h2-console